### ISSUE TITLE
Some questions about annotations

### ISSUE THREAD

**Issue by zugofn** [socome/MCSP-Multispectral-Pedestrian-detection#1]
Hi,thanks for your great work!
Can you share your annotations of "annotations-MBNet"(xml filetype) and "train_MBNet.txt"?
I have downloaded the annotations of MBNet,but the filetype of the annotations is ".npy".
Looking forward to your reply！
Have a good day！

**Comment by socome** [comment]
Umm... This repo was made only for a personal research. This code is not official... but if you want the annotation file, I will upload it tomorrow.

**Comment by zugofn** [comment]
> Umm... This repo was made only for a personal research. This code is not official... but if you want the annotation file, I will upload it tomorrow.

Wow！That's great. Thank you for your generosity！:) 형님

**Comment by socome** [comment]
pls, Check the new repo. Good Luck!

**Comment by zugofn** [comment]
> pls, Check the new repo. Good Luck!

So fast!Thank you again,Kind man!
Good Luck you too!Wuli 형님
